const copy={bn:{pilot:"পরীক্ষামূলক জনসেবা",title:"আপনার কাছের স্বাস্থ্যসেবা খুঁজুন",subtitle:"হাঁটা ও সড়কপথ মিলিয়ে সম্ভাব্য যাত্রার সময় দেখুন। এটি আনুমানিক—জরুরি অবস্থায় স্থানীয় জরুরি নম্বরে যোগাযোগ করুন।",district:"জেলা",searchLabel:"স্বাস্থ্যকেন্দ্র খুঁজুন",searchPlaceholder:"নাম বা ধরন",search:"খুঁজুন",locate:"⌖ আমার অবস্থানের কাছাকাছি",summary:"জেলার সারসংক্ষেপ",population:"আনুমানিক জনসংখ্যা",underserved:"২ ঘণ্টার বেশি দূরে",facilities:"মানচিত্রে কেন্দ্র",onlyUnderserved:"শুধু ২ ঘণ্টার বেশি",showUncertain:"অনিশ্চিত এলাকা দেখান",understand:"এই সময় কীভাবে হিসাব করা হয়েছে?",method:"WorldPop-এর ১ কিমি জনসংখ্যা সেল থেকে নিকটস্থ সড়ক পর্যন্ত ৩ কিমি/ঘণ্টা হাঁটা এবং OSRM সড়কযাত্রার সময় যোগ করা হয়েছে। পাহাড়, নৌপথ, আবহাওয়া ও সড়কের অবস্থা পুরোপুরি ধরা হয়নি।",sources:"তথ্য: HDX Healthsites, WorldPop, OpenStreetMap/Geofabrik ও geoBoundaries।",nearest:"নিকটতম তালিকাভুক্ত কেন্দ্র",minutes:"মিনিট",uncertain:"সড়ক থেকে দূরে—সময় বেশি অনিশ্চিত",noMatch:"কোনো মিল পাওয়া যায়নি।",locationError:"অবস্থান পাওয়া যায়নি। GPS অনুমতি ও সংযোগ পরীক্ষা করুন।"},en:{pilot:"Public pilot",title:"Find health services near you",subtitle:"Explore estimated walking and road journey times. These are estimates—contact local emergency services in an emergency.",district:"District",searchLabel:"Search facilities",searchPlaceholder:"Name or type",search:"Search",locate:"⌖ Near my location",summary:"District summary",population:"Estimated population",underserved:"More than 2 hours",facilities:"Mapped facilities",onlyUnderserved:"Only over 2 hours",showUncertain:"Show uncertain areas",understand:"How is this time calculated?",method:"The model adds walking at 3 km/h from each 1 km WorldPop cell to the nearest road and OSRM road travel. Terrain, boats, weather and road condition are not fully represented.",sources:"Data: HDX Healthsites, WorldPop, OpenStreetMap/Geofabrik and geoBoundaries.",nearest:"Nearest listed facility",minutes:"minutes",uncertain:"Far from a road—time is more uncertain",noMatch:"No matching facility found.",locationError:"Location unavailable. Check GPS permission and connectivity."}};
let language="bn",data,cellLayer,facilityLayer,userMarker;
const district=document.querySelector("#district"),message=document.querySelector("#message"),population=document.querySelector("#population"),underserved=document.querySelector("#underserved"),facilities=document.querySelector("#facilities"),search=document.querySelector("#search"),languageButton=document.querySelector("#language");
const map=L.map("map",{zoomControl:true}).setView([23.7,90.4],8);
L.tileLayer("https://{s}.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}{r}.png",{subdomains:"abcd",maxZoom:19,errorTileUrl:"tile-fallback.svg",updateWhenIdle:true,keepBuffer:3,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> &copy; <a href="https://carto.com/attributions">CARTO</a>'}).addTo(map);
const color=t=>t>120?"#b91c1c":t>90?"#ea580c":t>60?"#eab308":t>30?"#84cc16":"#059669";
const fmt=n=>new Intl.NumberFormat(language==="bn"?"bn-BD":"en-US",{maximumFractionDigits:0}).format(n);
function translate(){document.documentElement.lang=language;document.querySelectorAll("[data-i18n]").forEach(e=>e.textContent=copy[language][e.dataset.i18n]);document.querySelectorAll("[data-i18n-placeholder]").forEach(e=>e.placeholder=copy[language][e.dataset.i18nPlaceholder]);document.querySelector("#language").textContent=language==="bn"?"English":"বাংলা";if(data)render();}
function facilityPopup(f){return `<div class="facility-popup"><strong>${escapeHtml(f[2])}</strong><span>${escapeHtml(f[3]||"health facility")}</span></div>`}
function escapeHtml(value){const node=document.createElement("div");node.textContent=value;return node.innerHTML}
function render(){if(cellLayer)cellLayer.remove();if(facilityLayer)facilityLayer.remove();const only=document.querySelector("#onlyUnderserved").checked,showUncertain=document.querySelector("#showUncertain").checked;cellLayer=L.layerGroup(data.cells.filter(c=>(!only||c[4])&&(showUncertain||!c[5])).map(c=>L.circleMarker([c[1],c[0]],{radius:Math.max(2,Math.min(8,Math.sqrt(c[2])/12)),color:c[5]?"#111827":color(c[3]),weight:c[5]?1.5:0,fillColor:color(c[3]),fillOpacity:.65}).bindTooltip(`${fmt(c[3])} ${copy[language].minutes}${c[5]?`<br>${copy[language].uncertain}`:""}`))).addTo(map);facilityLayer=L.layerGroup(data.facilities.map(f=>L.circleMarker([f[1],f[0]],{radius:4,color:"#075985",weight:2,fillColor:"#fff",fillOpacity:1}).bindPopup(facilityPopup(f)))).addTo(map);const s=data.summary;population.textContent=fmt(s.estimated_population);underserved.textContent=`${fmt(s.population_over_threshold)} (${s.percent_population_over_threshold}%)`;facilities.textContent=fmt(data.facilities.length)}
async function loadDistrict(){message.textContent="";const slug=district.value;const response=await fetch(`data/${slug}.json`);if(!response.ok)throw new Error(`Data ${response.status}`);data=await response.json();render();const boundary=L.geoJSON(data.boundary);map.fitBounds(boundary.getBounds(),{padding:[15,15]})}
function distance(a,b){const r=6371,p=Math.PI/180,dLat=(b[0]-a[0])*p,dLon=(b[1]-a[1])*p;const h=Math.sin(dLat/2)**2+Math.cos(a[0]*p)*Math.cos(b[0]*p)*Math.sin(dLon/2)**2;return 2*r*Math.asin(Math.sqrt(h))}
function showNearest(lat,lon){const nearest=[...data.facilities].sort((a,b)=>distance([lat,lon],[a[1],a[0]])-distance([lat,lon],[b[1],b[0]]))[0];facilityLayer.eachLayer(layer=>{const ll=layer.getLatLng();if(Math.abs(ll.lat-nearest[1])<1e-5&&Math.abs(ll.lng-nearest[0])<1e-5)layer.openPopup()});message.textContent=`${copy[language].nearest}: ${nearest[2]} (${distance([lat,lon],[nearest[1],nearest[0]]).toFixed(1)} km straight-line)`;map.setView([lat,lon],13);if(userMarker)userMarker.remove();userMarker=L.marker([lat,lon]).addTo(map)}
district.addEventListener("change",()=>loadDistrict().catch(e=>message.textContent=e.message));languageButton.addEventListener("click",()=>{language=language==="bn"?"en":"bn";translate()});document.querySelector("#onlyUnderserved").addEventListener("change",render);document.querySelector("#showUncertain").addEventListener("change",render);document.querySelector("#searchButton").addEventListener("click",()=>{const q=search.value.trim().toLowerCase(),match=data.facilities.find(f=>f[2].toLowerCase().includes(q)||f[3].toLowerCase().includes(q));if(!q||!match){message.textContent=copy[language].noMatch;return}map.setView([match[1],match[0]],15);facilityLayer.eachLayer(l=>{const p=l.getLatLng();if(Math.abs(p.lat-match[1])<1e-5&&Math.abs(p.lng-match[0])<1e-5)l.openPopup()});message.textContent=""});document.querySelector("#locate").addEventListener("click",()=>navigator.geolocation?navigator.geolocation.getCurrentPosition(p=>showNearest(p.coords.latitude,p.coords.longitude),()=>message.textContent=copy[language].locationError,{enableHighAccuracy:true,timeout:10000}):message.textContent=copy[language].locationError);
if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("service-worker.js"));
translate();loadDistrict().catch(e=>message.textContent=e.message);
