const copy={
  bn:{pilot:"পরীক্ষামূলক জনসেবা",title:"আপনার কাছের স্বাস্থ্যসেবা খুঁজুন",subtitle:"হাঁটা ও সড়কপথ মিলিয়ে সম্ভাব্য যাত্রার সময় দেখুন। এটি আনুমানিক—জরুরি অবস্থায় স্থানীয় জরুরি নম্বরে যোগাযোগ করুন।",district:"এলাকা",searchLabel:"স্বাস্থ্যকেন্দ্র খুঁজুন",searchPlaceholder:"নাম বা ধরন",search:"খুঁজুন",locate:"⌖ আমার অবস্থানের কাছাকাছি",summary:"সারসংক্ষেপ",population:"আনুমানিক জনসংখ্যা",underserved:"২ ঘণ্টার বেশি দূরে",facilities:"মানচিত্রে কেন্দ্র",districts:"জেলা",highestGaps:"সর্বোচ্চ প্রবেশগম্যতার ঘাটতি",drillDown:"জেলার বিস্তারিত দেখুন",legend:"২ ঘণ্টার বেশি দূরে থাকা জনসংখ্যা",onlyUnderserved:"শুধু ২ ঘণ্টার বেশি",showUncertain:"অনিশ্চিত এলাকা দেখান",understand:"এই সময় কীভাবে হিসাব করা হয়েছে?",method:"WorldPop-এর ১ কিমি জনসংখ্যা সেল থেকে নিকটস্থ সড়ক পর্যন্ত ৩ কিমি/ঘণ্টা হাঁটা এবং OSRM সড়কযাত্রার সময় যোগ করা হয়েছে। পাহাড়, নৌপথ, আবহাওয়া ও সড়কের অবস্থা পুরোপুরি ধরা হয়নি।",sources:"তথ্য: HDX Healthsites, WorldPop, OpenStreetMap/Geofabrik ও geoBoundaries।",nearest:"নিকটতম তালিকাভুক্ত কেন্দ্র",minutes:"মিনিট",uncertain:"সড়ক থেকে দূরে—সময় বেশি অনিশ্চিত",noMatch:"কোনো মিল পাওয়া যায়নি।",locationError:"অবস্থান পাওয়া যায়নি। GPS অনুমতি ও সংযোগ পরীক্ষা করুন।",directions:"দিকনির্দেশ",report:"ভুল তথ্য",feedbackPilot:"অফলাইন পাইলট প্রতিক্রিয়া",reportTitle:"ভুল তথ্য জানান",issueType:"কী ভুল?",wrongLocation:"ভুল অবস্থান",closed:"বন্ধ বা নেই",wrongName:"ভুল নাম বা ধরন",other:"অন্যান্য",details:"বিস্তারিত",localOnly:"প্রতিবেদনটি এখন শুধু এই ডিভাইসে সংরক্ষিত হবে। ব্যক্তিগত স্বাস্থ্যতথ্য লিখবেন না।",cancel:"বাতিল",save:"ডিভাইসে সংরক্ষণ",saved:"প্রতিবেদনটি এই ডিভাইসে সংরক্ষিত হয়েছে।",submitted:"প্রতিবেদনটি পর্যালোচনার জন্য পাঠানো হয়েছে।",queued:"সংযোগ না থাকায় প্রতিবেদনটি ডিভাইসে রাখা হয়েছে; অনলাইনে এলে পাঠানো হবে।",unreachable:"সড়কপথে সংযোগ পাওয়া যায়নি"},
  en:{pilot:"Public pilot",title:"Find health services near you",subtitle:"Explore estimated walking and road journey times. These are estimates—contact local emergency services in an emergency.",district:"Area",searchLabel:"Search facilities",searchPlaceholder:"Name or type",search:"Search",locate:"⌖ Near my location",summary:"Summary",population:"Estimated population",underserved:"More than 2 hours",facilities:"Mapped facilities",districts:"Districts",highestGaps:"Highest access gaps",drillDown:"View district details",legend:"Population more than 2 hours away",onlyUnderserved:"Only over 2 hours",showUncertain:"Show uncertain areas",understand:"How is this time calculated?",method:"The model adds walking at 3 km/h from each 1 km WorldPop cell to the nearest road and OSRM road travel. Terrain, boats, weather and road condition are not fully represented.",sources:"Data: HDX Healthsites, WorldPop, OpenStreetMap/Geofabrik and geoBoundaries.",nearest:"Nearest listed facility",minutes:"minutes",uncertain:"Far from a road—time is more uncertain",noMatch:"No matching facility found.",locationError:"Location unavailable. Check GPS permission and connectivity.",directions:"Directions",report:"Report error",feedbackPilot:"Offline pilot feedback",reportTitle:"Report incorrect information",issueType:"What is wrong?",wrongLocation:"Wrong location",closed:"Closed or missing",wrongName:"Wrong name or type",other:"Other",details:"Details",localOnly:"The report is currently saved only on this device. Do not enter personal health information.",cancel:"Cancel",save:"Save on device",saved:"Report saved on this device.",submitted:"Report sent for review.",queued:"You appear to be offline. The report is queued on this device and will sync when online.",unreachable:"No routable road connection"}
};
const API_BASE=location.protocol==="https:"&&location.hostname==="localhost"?"https://shasthopath.krrkhan.com":"";
Object.assign(copy.bn,{facilityType:"কেন্দ্রের ধরন",allTypes:"সব ধরন",nearbyFacilities:"স্বাস্থ্যকেন্দ্রের তালিকা",results:"টি কেন্দ্র দেখানো হচ্ছে",share:"শেয়ার",copied:"লিংক কপি হয়েছে"});
Object.assign(copy.en,{facilityType:"Facility type",allTypes:"All types",nearbyFacilities:"Facility directory",results:"facilities shown",share:"Share",copied:"Link copied"});
Object.assign(copy.bn,{saveOffline:"অফলাইনের জন্য সংরক্ষণ করুন",removeOffline:"অফলাইন কপি মুছুন",downloading:"ডাউনলোড হচ্ছে",offlineReady:"অফলাইনে ব্যবহারের জন্য প্রস্তুত",offlineRemoved:"অফলাইন কপি মুছে ফেলা হয়েছে",offlineUnsupported:"এই ব্রাউজারে অফলাইন ডাউনলোড সমর্থিত নয়"});
Object.assign(copy.en,{saveOffline:"Save for offline use",removeOffline:"Remove offline copy",downloading:"Downloading",offlineReady:"Ready for offline use",offlineRemoved:"Offline copy removed",offlineUnsupported:"Offline downloads are not supported in this browser"});
Object.assign(copy.bn,{navMap:"মানচিত্র",navFind:"খুঁজুন",navNear:"কাছাকাছি",navDetails:"বিস্তারিত",locating:"আপনার অবস্থান খোঁজা হচ্ছে…",outsideCoverage:"আপনার অবস্থানের জেলা মানচিত্রে পাওয়া যায়নি।"});
Object.assign(copy.en,{navMap:"Map",navFind:"Find",navNear:"Nearby",navDetails:"Details",locating:"Finding your location…",outsideCoverage:"Your district could not be identified on the map."});
let language="bn",data,cellLayer,facilityLayer,userMarker,nationalLegend,catalog=[],facilityReference;
const district=document.querySelector("#district"),message=document.querySelector("#message"),population=document.querySelector("#population"),underserved=document.querySelector("#underserved"),facilities=document.querySelector("#facilities"),search=document.querySelector("#search"),languageButton=document.querySelector("#language"),ranking=document.querySelector("#nationalRanking"),thirdMetricLabel=document.querySelector("#thirdMetricLabel"),searchRow=document.querySelector(".search-row"),searchLabel=document.querySelector('label[for="search"]'),locateButton=document.querySelector("#locate"),toggles=document.querySelector(".toggles"),facilityFilters=document.querySelector("#facilityFilters"),facilityType=document.querySelector("#facilityType"),facilityDirectory=document.querySelector("#facilityDirectory"),resultCount=document.querySelector("#resultCount"),offlineControls=document.querySelector("#offlineControls"),offlineDownload=document.querySelector("#offlineDownload"),offlineStatus=document.querySelector("#offlineStatus"),mapElement=document.querySelector("#map"),findSection=document.querySelector("#findSection"),detailsSection=document.querySelector("#detailsSection"),mobileNav=document.querySelector("#mobileNav");
const map=L.map("map",{zoomControl:true}).setView([23.7,90.4],7);
L.tileLayer("https://a.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}.png",{maxZoom:19,errorTileUrl:"tile-fallback.svg",updateWhenIdle:true,keepBuffer:3,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> &copy; <a href="https://carto.com/attributions">CARTO</a>'}).addTo(map);
const color=t=>t===null?"#64748b":t>120?"#b91c1c":t>90?"#ea580c":t>60?"#eab308":t>30?"#84cc16":"#059669";
const gapColor=p=>p>10?"#991b1b":p>5?"#dc2626":p>2?"#f97316":p>1?"#facc15":p>0?"#84cc16":"#22c55e";
const fmt=n=>new Intl.NumberFormat(language==="bn"?"bn-BD":"en-US",{maximumFractionDigits:0}).format(n);
function translate(){document.documentElement.lang=language;document.querySelectorAll("[data-i18n]").forEach(e=>e.textContent=copy[language][e.dataset.i18n]);document.querySelectorAll("[data-i18n-placeholder]").forEach(e=>e.placeholder=copy[language][e.dataset.i18nPlaceholder]);languageButton.textContent=language==="bn"?"English":"বাংলা";for(const option of district.options){const item=catalog.find(entry=>entry.slug===option.value);if(item)option.textContent=language==="bn"?item.name_bn:item.name}if(data)render()}
function facilityPopup(f,index){return `<div class="facility-popup"><strong>${escapeHtml(f[2])}</strong><span>${escapeHtml(f[3]||"health facility")}</span><div class="popup-actions"><a href="https://www.google.com/maps/dir/?api=1&destination=${f[1]},${f[0]}" target="_blank" rel="noopener">${copy[language].directions}</a><button type="button" data-report-index="${index}">${copy[language].report}</button></div></div>`}
function escapeHtml(value){const node=document.createElement("div");node.textContent=value;return node.innerHTML}
function facilityEntries(){
  const query=search.value.trim().toLowerCase(),type=facilityType.value,center=facilityReference||[map.getCenter().lat,map.getCenter().lng];
  return data.facilities.map((facility,index)=>({facility,index,distance:distance(center,[facility[1],facility[0]])})).filter(({facility})=>(!type||facility[3]===type)&&(!query||facility[2].toLowerCase().includes(query)||facility[3].toLowerCase().includes(query))).sort((a,b)=>a.distance-b.distance)
}
function scrollToSection(node){node.scrollIntoView({behavior:"smooth",block:"start"});if(node===mapElement)setTimeout(()=>map.invalidateSize(),250)}
function openFacility(index){const facility=data.facilities[index];map.setView([facility[1],facility[0]],15);facilityLayer.eachLayer(layer=>{if(layer.options.facilityIndex===index)layer.openPopup()});scrollToSection(mapElement)}
function facilityUrl(index){const url=new URL(location.href);url.search="";url.searchParams.set("district",district.value);url.searchParams.set("facility",index);return url.href}
async function shareFacility(index){const facility=data.facilities[index],url=facilityUrl(index),payload={title:facility[2],text:facility[2],url};if(navigator.share){try{await navigator.share(payload);return}catch(error){if(error.name==="AbortError")return}}await navigator.clipboard.writeText(url);message.textContent=copy[language].copied}
function renderFacilityDirectory(){
  const entries=facilityEntries(),visible=entries.slice(0,20);resultCount.textContent=`${fmt(entries.length)} ${copy[language].results}`;
  facilityDirectory.querySelector("ol").replaceChildren(...visible.map(({facility,index,distance:km})=>{const item=document.createElement("li"),focus=document.createElement("button"),actions=document.createElement("div"),directions=document.createElement("a"),share=document.createElement("button");item.className="facility-result";focus.type="button";focus.innerHTML=`<strong>${escapeHtml(facility[2])}</strong><small>${escapeHtml(facility[3].replaceAll("_"," "))} · ${km.toFixed(1)} km</small>`;focus.addEventListener("click",()=>openFacility(index));actions.className="result-actions";directions.href=`https://www.google.com/maps/dir/?api=1&destination=${facility[1]},${facility[0]}`;directions.target="_blank";directions.rel="noopener";directions.textContent=copy[language].directions;share.type="button";share.textContent=copy[language].share;share.addEventListener("click",()=>shareFacility(index).catch(error=>message.textContent=error.message));actions.append(directions,share);item.append(focus,actions);return item}));
  if(facilityLayer)facilityLayer.remove();facilityLayer=L.layerGroup(entries.map(({facility,index})=>L.circleMarker([facility[1],facility[0]],{radius:4,color:"#075985",weight:2,fillColor:"#fff",fillOpacity:1,facilityIndex:index}).bindPopup(facilityPopup(facility,index)))).addTo(map);facilities.textContent=fmt(entries.length)
}
const OFFLINE_CACHE="shasthopath-districts-v1",offlineKey="shasthopath-offline-districts";
const savedDistricts=()=>JSON.parse(localStorage.getItem(offlineKey)||"{}");
function tileCoordinate(lon,lat,zoom){const scale=2**zoom,x=Math.floor((lon+180)/360*scale),limited=Math.max(-85.0511,Math.min(85.0511,lat)),y=Math.floor((1-Math.asinh(Math.tan(limited*Math.PI/180))/Math.PI)/2*scale);return [x,y]}
function offlineUrls(){const bounds=L.geoJSON(data.boundary).getBounds(),urls=[new URL(`data/${district.value}.json`,location.href).href];for(let zoom=8;zoom<=11;zoom++){const [minX,maxY]=tileCoordinate(bounds.getWest(),bounds.getSouth(),zoom),[maxX,minY]=tileCoordinate(bounds.getEast(),bounds.getNorth(),zoom);for(let x=minX;x<=maxX;x++)for(let y=minY;y<=maxY;y++)urls.push(`https://a.basemaps.cartocdn.com/rastertiles/voyager/${zoom}/${x}/${y}.png`)}return urls.slice(0,180)}
function updateOfflineStatus(){const saved=savedDistricts()[district.value];offlineDownload.textContent=saved?copy[language].removeOffline:copy[language].saveOffline;offlineStatus.textContent=saved?copy[language].offlineReady:""}
async function cacheOfflineDistrict(){
  if(!("caches" in window)){offlineStatus.textContent=copy[language].offlineUnsupported;return}
  const saved=savedDistricts(),slug=district.value,cache=await caches.open(OFFLINE_CACHE);
  if(saved[slug]){for(const url of saved[slug].urls)await cache.delete(url);delete saved[slug];localStorage.setItem(offlineKey,JSON.stringify(saved));offlineStatus.textContent=copy[language].offlineRemoved;offlineDownload.textContent=copy[language].saveOffline;return}
  const urls=offlineUrls();offlineDownload.disabled=true;let completed=0,failures=0;
  for(let start=0;start<urls.length;start+=6){await Promise.all(urls.slice(start,start+6).map(async url=>{try{const response=await fetch(url,{mode:url.startsWith(location.origin)?"same-origin":"no-cors"});await cache.put(url,response)}catch{failures++}finally{completed++;offlineStatus.textContent=`${copy[language].downloading} ${fmt(completed)}/${fmt(urls.length)}`}}))}
  saved[slug]={saved_at:new Date().toISOString(),urls};localStorage.setItem(offlineKey,JSON.stringify(saved));offlineDownload.disabled=false;offlineDownload.textContent=copy[language].removeOffline;offlineStatus.textContent=`${copy[language].offlineReady}${failures?` (${failures} unavailable)`:""}`
}
function clearLayers(){if(cellLayer)cellLayer.remove();if(facilityLayer)facilityLayer.remove();if(nationalLegend){nationalLegend.remove();nationalLegend=null}}
async function setDistrict(slug){district.value=slug;const url=new URL(location.href);url.search="";if(slug!=="national")url.searchParams.set("district",slug);history.replaceState(null,"",url);facilityReference=null;search.value="";facilityType.value="";await loadDistrict()}
function districtName(properties){return language==="bn"?properties.name_bn:properties.name}
function renderNational(){
  searchLabel.hidden=searchRow.hidden=locateButton.hidden=toggles.hidden=facilityFilters.hidden=facilityDirectory.hidden=offlineControls.hidden=true;for(const node of [searchLabel,searchRow,locateButton,toggles,facilityFilters,facilityDirectory,offlineControls])node.style.display="none";ranking.hidden=false;ranking.style.display="";thirdMetricLabel.textContent=copy[language].districts;
  cellLayer=L.geoJSON(data.districts,{style:feature=>({color:"#fff",weight:1.5,fillColor:gapColor(feature.properties.percent_over_threshold),fillOpacity:.78}),onEachFeature:(feature,layer)=>{const p=feature.properties;layer.bindTooltip(`<strong>${escapeHtml(districtName(p))}</strong><br>${p.percent_over_threshold}% · ${fmt(p.population_over_threshold)}`);layer.bindPopup(`<div class="facility-popup"><strong>${escapeHtml(districtName(p))}</strong><span>${fmt(p.population_over_threshold)} (${p.percent_over_threshold}%)</span><div class="popup-actions"><button type="button" data-district-slug="${p.slug}">${copy[language].drillDown}</button></div></div>`)}}).addTo(map);
  const s=data.summary;population.textContent=fmt(s.estimated_population);underserved.textContent=`${fmt(s.population_over_threshold)} (${s.percent_over_threshold}%)`;facilities.textContent=fmt(s.districts);
  const top=[...data.districts.features].sort((a,b)=>b.properties.percent_over_threshold-a.properties.percent_over_threshold).slice(0,6);ranking.querySelector("ol").replaceChildren(...top.map(feature=>{const p=feature.properties,item=document.createElement("li"),button=document.createElement("button");button.type="button";button.textContent=`${districtName(p)} — ${p.percent_over_threshold}%`;button.addEventListener("click",()=>setDistrict(p.slug));item.append(button);return item}));
  nationalLegend=L.control({position:"bottomright"});nationalLegend.onAdd=()=>{const node=L.DomUtil.create("div","national-legend");node.innerHTML=`<strong>${copy[language].legend}</strong><span><i style="background:#22c55e"></i>0%</span><span><i style="background:#84cc16"></i>0–1%</span><span><i style="background:#facc15"></i>1–2%</span><span><i style="background:#f97316"></i>2–5%</span><span><i style="background:#dc2626"></i>5–10%</span><span><i style="background:#991b1b"></i>&gt;10%</span>`;node.style.maxWidth="calc(100vw - 24px)";node.querySelector("strong").style.display="block";node.querySelectorAll("span").forEach(item=>{item.style.display="inline-block";item.style.marginRight="6px"});return node};nationalLegend.addTo(map)
}
function renderDistrict(){
  searchLabel.hidden=searchRow.hidden=locateButton.hidden=toggles.hidden=facilityFilters.hidden=facilityDirectory.hidden=offlineControls.hidden=false;for(const node of [searchLabel,searchRow,locateButton,toggles,facilityFilters,facilityDirectory,offlineControls])node.style.display="";ranking.hidden=true;ranking.style.display="none";thirdMetricLabel.textContent=copy[language].facilities;updateOfflineStatus();
  const only=document.querySelector("#onlyUnderserved").checked,showUncertain=document.querySelector("#showUncertain").checked;
  cellLayer=L.layerGroup(data.cells.filter(c=>(!only||c[4])&&(showUncertain||!c[5])).map(c=>L.circleMarker([c[1],c[0]],{radius:Math.max(2,Math.min(8,Math.sqrt(c[2])/12)),color:c[5]?"#111827":color(c[3]),weight:c[5]?1.5:0,fillColor:color(c[3]),fillOpacity:.65}).bindTooltip(`${c[3]===null?copy[language].unreachable:`${fmt(c[3])} ${copy[language].minutes}`}${c[5]?`<br>${copy[language].uncertain}`:""}`))).addTo(map);
  const currentType=facilityType.value,types=[...new Set(data.facilities.map(f=>f[3]).filter(Boolean))].sort();facilityType.replaceChildren(...["",...types].map(type=>{const option=document.createElement("option");option.value=type;option.textContent=type?type.replaceAll("_"," "):copy[language].allTypes;return option}));if(types.includes(currentType))facilityType.value=currentType;
  renderFacilityDirectory();const s=data.summary;population.textContent=fmt(s.estimated_population);underserved.textContent=`${fmt(s.population_over_threshold)} (${s.percent_population_over_threshold}%)`
}
function render(){clearLayers();if(data.schema==="facility-access-national-v1")renderNational();else renderDistrict()}
async function loadDistrict(){message.textContent="";const response=await fetch(`data/${district.value}.json`);if(!response.ok)throw new Error(`Data ${response.status}`);data=await response.json();render();const geometry=data.schema==="facility-access-national-v1"?data.districts:data.boundary;map.fitBounds(L.geoJSON(geometry).getBounds(),{padding:[15,15]})}
async function loadCatalog(){const response=await fetch("data/catalog.json");if(!response.ok)throw new Error(`Catalog ${response.status}`);const payload=await response.json();catalog=[payload.national,...payload.districts];district.replaceChildren(...catalog.map(item=>{const option=document.createElement("option");option.value=item.slug;option.textContent=language==="bn"?item.name_bn:item.name;return option}));const requested=new URL(location.href).searchParams.get("district");district.value=catalog.some(item=>item.slug===requested)?requested:"national"}
function distance(a,b){const r=6371,p=Math.PI/180,dLat=(b[0]-a[0])*p,dLon=(b[1]-a[1])*p;const h=Math.sin(dLat/2)**2+Math.cos(a[0]*p)*Math.cos(b[0]*p)*Math.sin(dLon/2)**2;return 2*r*Math.asin(Math.sqrt(h))}
function showNearest(lat,lon){if(!data.facilities?.length)return;facilityReference=[lat,lon];search.value="";facilityType.value="";renderFacilityDirectory();const nearest=facilityEntries()[0].facility;facilityLayer.eachLayer(layer=>{const ll=layer.getLatLng();if(Math.abs(ll.lat-nearest[1])<1e-5&&Math.abs(ll.lng-nearest[0])<1e-5)layer.openPopup()});message.textContent=`${copy[language].nearest}: ${nearest[2]} (${distance([lat,lon],[nearest[1],nearest[0]]).toFixed(1)} km straight-line)`;map.setView([lat,lon],13);if(userMarker)userMarker.remove();userMarker=L.marker([lat,lon]).addTo(map);scrollToSection(mapElement)}
function pointInRing(lon,lat,ring){let inside=false;for(let i=0,j=ring.length-1;i<ring.length;j=i++){const [xi,yi]=ring[i],[xj,yj]=ring[j],cross=(yi>lat)!==(yj>lat)&&lon<(xj-xi)*(lat-yi)/(yj-yi)+xi;if(cross)inside=!inside}return inside}
function pointInGeometry(lon,lat,geometry){const polygonContains=polygon=>pointInRing(lon,lat,polygon[0])&&!polygon.slice(1).some(ring=>pointInRing(lon,lat,ring));if(geometry.type==="Polygon")return polygonContains(geometry.coordinates);if(geometry.type==="MultiPolygon")return geometry.coordinates.some(polygonContains);return false}
function nativeGeolocation(){return window.Capacitor?.Plugins?.Geolocation}
async function currentPosition(){const native=nativeGeolocation();if(native){const permission=await native.checkPermissions();if(permission.location!=="granted"&&permission.coarseLocation!=="granted"){const requested=await native.requestPermissions();if(requested.location!=="granted"&&requested.coarseLocation!=="granted")throw new Error("Location permission denied")}return native.getCurrentPosition({enableHighAccuracy:true,timeout:15000,maximumAge:30000})}if(!navigator.geolocation)throw new Error("Geolocation unavailable");return new Promise((resolve,reject)=>navigator.geolocation.getCurrentPosition(resolve,reject,{enableHighAccuracy:true,timeout:15000,maximumAge:30000}))}
async function locateAndShow(){locateButton.disabled=true;message.textContent=copy[language].locating;try{const position=await currentPosition(),{latitude,longitude}=position.coords;if(data.schema==="facility-access-national-v1"){const match=data.districts.features.find(feature=>pointInGeometry(longitude,latitude,feature.geometry));if(!match){message.textContent=copy[language].outsideCoverage;return}await setDistrict(match.properties.slug)}showNearest(latitude,longitude)}catch(error){console.warn("Location failed",error);message.textContent=copy[language].locationError}finally{locateButton.disabled=false}}
window.selectDistrict=setDistrict;
map.on("popupopen",event=>{const popup=event.popup.getElement(),reportButton=popup?.querySelector("[data-report-index]"),districtButton=popup?.querySelector("[data-district-slug]");if(reportButton)reportButton.addEventListener("click",()=>openReport(Number(reportButton.dataset.reportIndex)),{once:true});if(districtButton)districtButton.addEventListener("click",()=>setDistrict(districtButton.dataset.districtSlug),{once:true})});
district.addEventListener("change",()=>setDistrict(district.value).catch(e=>message.textContent=e.message));languageButton.addEventListener("click",()=>{language=language==="bn"?"en":"bn";translate()});document.querySelector("#onlyUnderserved").addEventListener("change",render);document.querySelector("#showUncertain").addEventListener("change",render);document.querySelector("#searchButton").addEventListener("click",()=>{if(!data.facilities)return;renderFacilityDirectory();const match=facilityEntries()[0];if(!match){message.textContent=copy[language].noMatch;return}openFacility(match.index);message.textContent=""});search.addEventListener("keydown",event=>{if(event.key==="Enter")document.querySelector("#searchButton").click()});facilityType.addEventListener("change",()=>{message.textContent="";renderFacilityDirectory()});locateButton.addEventListener("click",locateAndShow);mobileNav.addEventListener("click",event=>{const button=event.target.closest("[data-mobile-action]");if(!button)return;const action=button.dataset.mobileAction;if(action==="map")scrollToSection(mapElement);if(action==="find"){scrollToSection(findSection);setTimeout(()=>search.focus({preventScroll:true}),300)}if(action==="near")locateAndShow();if(action==="details")scrollToSection(detailsSection)});offlineDownload.addEventListener("click",()=>cacheOfflineDistrict().catch(error=>{offlineDownload.disabled=false;offlineStatus.textContent=error.message}));
if("serviceWorker" in navigator){let refreshing=false;navigator.serviceWorker.addEventListener("controllerchange",()=>{if(!refreshing){refreshing=true;window.location.reload()}});window.addEventListener("load",()=>navigator.serviceWorker.register("service-worker.js"))}
window.openReport=index=>{const facility=data.facilities[index],dialog=document.querySelector("#reportDialog");document.querySelector("#reportFacility").textContent=facility[2];document.querySelector("#reportFacilityData").value=JSON.stringify({district:data.district,facility});document.querySelector("#issueNote").value="";dialog.showModal()};
const readReports=()=>JSON.parse(localStorage.getItem("shasthopath-reports")||"[]"),writeReports=reports=>localStorage.setItem("shasthopath-reports",JSON.stringify(reports));
async function sendReport(report){const response=await fetch(`${API_BASE}/api/reports`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(report)});if(!response.ok)throw new Error(`Report API ${response.status}`);return response.json()}
async function flushReports(){const reports=readReports();let changed=false;for(const report of reports.filter(item=>item.status==="device-only")){try{const result=await sendReport(report);report.status="submitted";report.server_id=result.id;changed=true}catch{return}}if(changed)writeReports(reports)}
document.querySelector("#reportForm").addEventListener("submit",async event=>{if(event.submitter?.value==="cancel")return;event.preventDefault();const report={local_id:crypto.randomUUID?.()||String(Date.now()),facility:JSON.parse(document.querySelector("#reportFacilityData").value),issue:document.querySelector("#issueType").value,note:document.querySelector("#issueNote").value.trim(),created_at:new Date().toISOString(),status:"device-only"},reports=readReports();reports.push(report);writeReports(reports);document.querySelector("#reportDialog").close();try{const result=await sendReport(report);report.status="submitted";report.server_id=result.id;writeReports(reports);message.textContent=copy[language].submitted}catch{message.textContent=copy[language].queued}});
window.addEventListener("online",flushReports);
async function initialize(){translate();await loadCatalog();await loadDistrict();const requested=Number.parseInt(new URL(location.href).searchParams.get("facility"),10);if(data.facilities&&Number.isInteger(requested)&&requested>=0&&requested<data.facilities.length)openFacility(requested);flushReports()}initialize().catch(error=>message.textContent=error.message);
