const API_BASE=location.protocol==="https:"&&location.hostname==="localhost"?"https://shasthopath.krrkhan.com":"";
const FALLBACK_VERSION="1.1.1";
const currentVersion=document.querySelector("#currentVersion"),latestVersion=document.querySelector("#latestVersion"),status=document.querySelector("#updateStatus"),updateNow=document.querySelector("#updateNow"),checkAgain=document.querySelector("#checkAgain");
let release;
const updater=()=>window.Capacitor?.Plugins?.AppUpdater;
function compareVersions(left,right){const a=left.split(".").map(Number),b=right.split(".").map(Number);for(let index=0;index<Math.max(a.length,b.length);index++){const difference=(a[index]||0)-(b[index]||0);if(difference)return difference}return 0}
function setStatus(text,type=""){status.textContent=text;status.className=`update-status${type?` ${type}`:""}`}
async function installedVersion(){if(updater())return (await updater().getCurrentVersion()).version;return FALLBACK_VERSION}
async function checkForUpdate(){checkAgain.disabled=true;updateNow.hidden=true;setStatus("সংস্করণ পরীক্ষা করা হচ্ছে…");try{const [installed,response]=await Promise.all([installedVersion(),fetch(`${API_BASE}/app-version.json`,{cache:"no-store"})]);if(!response.ok)throw new Error(`Version service ${response.status}`);release=await response.json();currentVersion.textContent=installed;latestVersion.textContent=release.version;if(compareVersions(installed,release.version)<0){updateNow.hidden=false;setStatus(`সংস্করণ ${release.version} পাওয়া গেছে। আপনি চাইলে এখন আপডেট করতে পারেন।`)}else setStatus("আপনি স্বাস্থ্যপথের সর্বশেষ সংস্করণ ব্যবহার করছেন।","success")}catch(error){console.warn(error);setStatus("এখন সংস্করণ পরীক্ষা করা যাচ্ছে না। সংযোগ পরীক্ষা করে আবার চেষ্টা করুন।","error")}finally{checkAgain.disabled=false}}
async function installUpdate(){if(!release)return;const native=updater();if(!native){setStatus("অ্যাপের ভেতরের আপডেট Android অ্যাপে পাওয়া যায়।","error");return}updateNow.disabled=true;updateNow.textContent="ডাউনলোড ও যাচাই হচ্ছে…";setStatus("আপডেট ডাউনলোড হচ্ছে। অ্যাপটি বন্ধ করবেন না।");try{await native.installUpdate({url:release.apk_url,sha256:release.sha256});setStatus("আপডেট যাচাই হয়েছে। Android ইনস্টল নিশ্চিত করুন।","success")}catch(error){const permissionRequired=error?.code==="INSTALL_PERMISSION_REQUIRED"||String(error?.message||error).includes("Allow updates");setStatus(permissionRequired?"Android সেটিংসে ‘Allow from this source’ চালু করুন, ফিরে এসে আবার ‘এখনই আপডেট করুন’ চাপুন।":"আপডেট সম্পন্ন হয়নি। আবার চেষ্টা করুন।","error")}finally{updateNow.disabled=false;updateNow.textContent="এখনই আপডেট করুন"}}
updateNow.addEventListener("click",installUpdate);checkAgain.addEventListener("click",checkForUpdate);checkForUpdate();
